import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type Role = "matelematics_admin" | "partner_admin" | "client_admin" | "user";
type Profile = { id: string; role: Role; company_id: string | null; partner_id: string | null };

function isRole(value: unknown): value is Role { return value === "matelematics_admin" || value === "partner_admin" || value === "client_admin" || value === "user"; }
const supabaseUrl = process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL;
const secretKey = process.env.SUPABASE_SECRET_KEY;
const publishableKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
function getAdmin(){ if(!supabaseUrl||!secretKey) throw new Error("Configuration Supabase serveur absente."); return createClient(supabaseUrl,secretKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}); }
async function authenticate(request:NextRequest){ const authorization=request.headers.get("authorization"); const token=authorization?.startsWith("Bearer ")?authorization.slice(7):null; if(!token)throw new Error("AUTH_REQUIRED"); const admin=getAdmin(); const {data:userData,error:userError}=await admin.auth.getUser(token); if(userError||!userData.user)throw new Error("AUTH_REQUIRED"); const {data:profile,error:profileError}=await admin.from("profiles").select("id,role,company_id,partner_id").eq("id",userData.user.id).single(); if(profileError||!profile)throw new Error("PROFILE_REQUIRED"); if(!isRole(profile.role))throw new Error("FORBIDDEN"); return {admin,profile:profile as Profile,token}; }
async function allowedCompanyIds(admin:ReturnType<typeof getAdmin>,profile:Profile):Promise<string[]|null>{ if(profile.role==="matelematics_admin")return null; if(profile.role==="client_admin"||profile.role==="user")return profile.company_id?[profile.company_id]:[]; if(!profile.partner_id)return[]; const {data,error}=await admin.from("companies").select("id").eq("partner_id",profile.partner_id); if(error)throw error; return(data??[]).map(c=>c.id); }
function canManage(profile:Profile){return profile.role==="matelematics_admin"||profile.role==="partner_admin"||profile.role==="client_admin";}
async function getAvailableVehicles(admin:ReturnType<typeof getAdmin>,companyIds:string[]|null){ let q=admin.from("vehicles").select("id,company_id,name,registration,status").neq("status","inactive").order("name"); if(companyIds!==null)q=q.in("company_id",companyIds); const {data:vehicles,error}=await q;if(error)throw error;if(!vehicles?.length)return[]; const ids=vehicles.map(v=>v.id);const {data:assignments,error:ae}=await admin.from("vehicle_driver_assignments").select("vehicle_id").in("vehicle_id",ids).eq("status","active").is("unassigned_at",null);if(ae)throw ae;const assigned=new Set((assignments??[]).map(a=>a.vehicle_id));const companyIds2=Array.from(new Set(vehicles.map(v=>v.company_id)));const {data:companies,error:ce}=await admin.from("companies").select("id,name").in("id",companyIds2);if(ce)throw ce;const names=new Map((companies??[]).map(c=>[c.id,c.name]));return vehicles.filter(v=>!assigned.has(v.id)).map(v=>({id:v.id,companyId:v.company_id,companyName:names.get(v.company_id)??"Client",name:v.name,registration:v.registration})); }

export async function GET(request:NextRequest){try{const {admin,profile}=await authenticate(request);const companyIds=await allowedCompanyIds(admin,profile);const manageable=canManage(profile);const availableVehicles=manageable?await getAvailableVehicles(admin,companyIds):[];if(companyIds!==null&&companyIds.length===0)return NextResponse.json({drivers:[],canCreate:manageable,canUpdate:manageable,availableVehicles});let q=admin.from("drivers").select("id,company_id,full_name,license_number,phone,status,created_at,updated_at").order("full_name");if(companyIds!==null)q=q.in("company_id",companyIds);const {data:drivers,error}=await q;if(error)throw error;const rows=drivers??[];if(!rows.length)return NextResponse.json({drivers:[],canCreate:manageable,canUpdate:manageable,availableVehicles});const driverIds=rows.map(d=>d.id),companySet=Array.from(new Set(rows.map(d=>d.company_id)));const [{data:assignments,error:ae},{data:companies,error:ce}]=await Promise.all([admin.from("vehicle_driver_assignments").select("id,company_id,vehicle_id,driver_id,assigned_at,status").in("driver_id",driverIds).eq("status","active").is("unassigned_at",null),admin.from("companies").select("id,name").in("id",companySet)]);if(ae)throw ae;if(ce)throw ce;const active=assignments??[],vehicleIds=Array.from(new Set(active.map(a=>a.vehicle_id)));const {data:vehicles,error:ve}=vehicleIds.length?await admin.from("vehicles").select("id,name,registration,status").in("id",vehicleIds):{data:[],error:null};if(ve)throw ve;const byDriver=new Map(active.map(a=>[a.driver_id,a])),byVehicle=new Map((vehicles??[]).map(v=>[v.id,v])),byCompany=new Map((companies??[]).map(c=>[c.id,c.name]));const result=rows.map(d=>{const a=byDriver.get(d.id)??null,v=a?byVehicle.get(a.vehicle_id)??null:null;return{id:d.id,companyId:d.company_id,companyName:byCompany.get(d.company_id)??"Client",fullName:d.full_name,licenseNumber:d.license_number,phone:d.phone,status:d.status,createdAt:d.created_at,updatedAt:d.updated_at,activeAssignment:a?{id:a.id,assignedAt:a.assigned_at,vehicle:v?{id:v.id,name:v.name,registration:v.registration,status:v.status}:null}:null};});return NextResponse.json({drivers:result,canCreate:manageable,canUpdate:manageable,availableVehicles});}catch(error){console.error("[Drivers API]",error);const m=error instanceof Error?error.message:"Erreur serveur.";if(m==="AUTH_REQUIRED")return NextResponse.json({error:"Authentification requise."},{status:401});if(m==="PROFILE_REQUIRED"||m==="FORBIDDEN")return NextResponse.json({error:"Accès refusé."},{status:403});return NextResponse.json({error:m},{status:500});}}

function scopedClient(token:string){if(!supabaseUrl||!publishableKey)throw new Error("Configuration Supabase publique absente.");return createClient(supabaseUrl,publishableKey,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});}
function rpcError(detail:string){if(detail.includes("VEHICLE_ALREADY_ASSIGNED"))return NextResponse.json({error:"Ce véhicule possède déjà un conducteur actif."},{status:409});if(detail.includes("VEHICLE_NOT_ACCESSIBLE")||detail.includes("DRIVER_NOT_ACCESSIBLE")||detail.includes("FORBIDDEN"))return NextResponse.json({error:"Conducteur ou véhicule inaccessible dans votre périmètre."},{status:403});if(detail.includes("VEHICLE_REQUIRED"))return NextResponse.json({error:"La sélection d’un véhicule est obligatoire."},{status:400});return null;}

export async function POST(request:NextRequest){try{const {profile,token}=await authenticate(request);if(!canManage(profile))return NextResponse.json({error:"Modification interdite pour ce rôle."},{status:403});const body=await request.json() as {fullName?:unknown;licenseNumber?:unknown;phone?:unknown;vehicleId?:unknown;companyId?:unknown};const fullName=typeof body.fullName==="string"?body.fullName.trim():"",vehicleId=typeof body.vehicleId==="string"?body.vehicleId:"",companyId=typeof body.companyId==="string"?body.companyId:"",license=typeof body.licenseNumber==="string"?body.licenseNumber.trim():"",phone=typeof body.phone==="string"?body.phone.trim():"";if(!fullName)return NextResponse.json({error:"Le nom du conducteur est obligatoire."},{status:400});if(!vehicleId||!companyId)return NextResponse.json({error:"La sélection d’un véhicule est obligatoire."},{status:400});const {data,error}=await scopedClient(token).rpc("create_driver_with_assignment",{p_company_id:companyId,p_vehicle_id:vehicleId,p_full_name:fullName,p_license_number:license||null,p_phone:phone||null});if(error){const detail=`${error.message} ${error.details??""}`;const mapped=rpcError(detail);if(mapped)return mapped;throw error;}return NextResponse.json({driverId:data},{status:201});}catch(error){console.error("[Drivers API POST]",error);const m=error instanceof Error?error.message:"Erreur serveur.";if(m==="AUTH_REQUIRED")return NextResponse.json({error:"Authentification requise."},{status:401});if(m==="PROFILE_REQUIRED"||m==="FORBIDDEN")return NextResponse.json({error:"Accès refusé."},{status:403});return NextResponse.json({error:m},{status:500});}}

export async function PATCH(request:NextRequest){try{const {profile,token}=await authenticate(request);if(!canManage(profile))return NextResponse.json({error:"Modification interdite pour ce rôle."},{status:403});const body=await request.json() as {driverId?:unknown;fullName?:unknown;licenseNumber?:unknown;phone?:unknown;vehicleId?:unknown};const driverId=typeof body.driverId==="string"?body.driverId:"",fullName=typeof body.fullName==="string"?body.fullName.trim():"",vehicleId=typeof body.vehicleId==="string"?body.vehicleId:"",license=typeof body.licenseNumber==="string"?body.licenseNumber.trim():"",phone=typeof body.phone==="string"?body.phone.trim():"";if(!driverId)return NextResponse.json({error:"Conducteur obligatoire."},{status:400});if(!fullName)return NextResponse.json({error:"Le nom du conducteur est obligatoire."},{status:400});if(!vehicleId)return NextResponse.json({error:"La sélection d’un véhicule est obligatoire."},{status:400});const {data,error}=await scopedClient(token).rpc("update_driver_with_assignment",{p_driver_id:driverId,p_full_name:fullName,p_license_number:license||null,p_phone:phone||null,p_vehicle_id:vehicleId});if(error){const detail=`${error.message} ${error.details??""}`;const mapped=rpcError(detail);if(mapped)return mapped;throw error;}return NextResponse.json({driverId:data});}catch(error){console.error("[Drivers API PATCH]",error);const m=error instanceof Error?error.message:"Erreur serveur.";if(m==="AUTH_REQUIRED")return NextResponse.json({error:"Authentification requise."},{status:401});if(m==="PROFILE_REQUIRED"||m==="FORBIDDEN")return NextResponse.json({error:"Accès refusé."},{status:403});return NextResponse.json({error:m},{status:500});}}
