import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
type Role = "matelematics_admin" | "partner_admin" | "client_admin" | "user";
type Profile = { id:string; role:Role; company_id:string|null; partner_id:string|null };
function isRole(v:unknown):v is Role{return v==="matelematics_admin"||v==="partner_admin"||v==="client_admin"||v==="user";}
const supabaseUrl=process.env.SUPABASE_URL??process.env.NEXT_PUBLIC_SUPABASE_URL,secretKey=process.env.SUPABASE_SECRET_KEY,publishableKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
function getAdmin(){if(!supabaseUrl||!secretKey)throw new Error("Configuration Supabase serveur absente.");return createClient(supabaseUrl,secretKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});}
async function authenticate(request:NextRequest){const h=request.headers.get("authorization"),token=h?.startsWith("Bearer ")?h.slice(7):null;if(!token)throw new Error("AUTH_REQUIRED");const admin=getAdmin();const {data:u,error:ue}=await admin.auth.getUser(token);if(ue||!u.user)throw new Error("AUTH_REQUIRED");const {data:p,error:pe}=await admin.from("profiles").select("id,role,company_id,partner_id").eq("id",u.user.id).single();if(pe||!p)throw new Error("PROFILE_REQUIRED");if(!isRole(p.role))throw new Error("FORBIDDEN");return{admin,profile:p as Profile,token};}
async function allowedCompanyIds(admin:ReturnType<typeof getAdmin>,p:Profile):Promise<string[]|null>{if(p.role==="matelematics_admin")return null;if(p.role==="client_admin"||p.role==="user")return p.company_id?[p.company_id]:[];if(!p.partner_id)return[];const {data,error}=await admin.from("companies").select("id").eq("partner_id",p.partner_id);if(error)throw error;return(data??[]).map(c=>c.id);}
function canManage(p:Profile){return p.role==="matelematics_admin"||p.role==="partner_admin"||p.role==="client_admin";}
function scopedClient(token:string){if(!supabaseUrl||!publishableKey)throw new Error("Configuration Supabase publique absente.");return createClient(supabaseUrl,publishableKey,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});}
function rpcError(detail:string){if(detail.includes("VEHICLE_ALREADY_ASSIGNED"))return NextResponse.json({error:"Ce véhicule possède déjà un conducteur actif."},{status:409});if(detail.includes("NO_ACTIVE_ASSIGNMENT"))return NextResponse.json({error:"Ce conducteur n’a aucune affectation active."},{status:409});if(detail.includes("VEHICLE_NOT_ACCESSIBLE")||detail.includes("DRIVER_NOT_ACCESSIBLE")||detail.includes("FORBIDDEN"))return NextResponse.json({error:"Conducteur ou véhicule inaccessible dans votre périmètre."},{status:403});if(detail.includes("VEHICLE_REQUIRED"))return NextResponse.json({error:"La sélection d’un véhicule est obligatoire."},{status:400});return null;}
function caught(error:unknown,label:string){console.error(label,error);const m=error instanceof Error?error.message:"Erreur serveur.";if(m==="AUTH_REQUIRED")return NextResponse.json({error:"Authentification requise."},{status:401});if(m==="PROFILE_REQUIRED"||m==="FORBIDDEN")return NextResponse.json({error:"Accès refusé."},{status:403});return NextResponse.json({error:m},{status:500});}
async function availableVehicles(admin:ReturnType<typeof getAdmin>,ids:string[]|null){let q=admin.from("vehicles").select("id,company_id,name,registration,status").neq("status","inactive").order("name");if(ids!==null)q=q.in("company_id",ids);const {data:v,error}=await q;if(error)throw error;if(!v?.length)return[];const {data:a,error:ae}=await admin.from("vehicle_driver_assignments").select("vehicle_id").in("vehicle_id",v.map(x=>x.id)).eq("status","active").is("unassigned_at",null);if(ae)throw ae;const assigned=new Set((a??[]).map(x=>x.vehicle_id)),cids=Array.from(new Set(v.map(x=>x.company_id)));const {data:c,error:ce}=await admin.from("companies").select("id,name").in("id",cids);if(ce)throw ce;const names=new Map((c??[]).map(x=>[x.id,x.name]));return v.filter(x=>!assigned.has(x.id)).map(x=>({id:x.id,companyId:x.company_id,companyName:names.get(x.company_id)??"Client",name:x.name,registration:x.registration}));}

export async function GET(request:NextRequest){try{const {admin,profile}=await authenticate(request),ids=await allowedCompanyIds(admin,profile),manageable=canManage(profile),av=manageable?await availableVehicles(admin,ids):[];if(ids!==null&&!ids.length)return NextResponse.json({drivers:[],canCreate:manageable,canUpdate:manageable,canDelete:manageable,availableVehicles:av});let q=admin.from("drivers").select("id,company_id,full_name,license_number,phone,status,created_at,updated_at").order("full_name");if(ids!==null)q=q.in("company_id",ids);const {data:d,error}=await q;if(error)throw error;const rows=d??[];if(!rows.length)return NextResponse.json({drivers:[],canCreate:manageable,canUpdate:manageable,canDelete:manageable,availableVehicles:av});const dids=rows.map(x=>x.id),cids=Array.from(new Set(rows.map(x=>x.company_id)));const [{data:a,error:ae},{data:c,error:ce}]=await Promise.all([admin.from("vehicle_driver_assignments").select("id,company_id,vehicle_id,driver_id,assigned_at,status").in("driver_id",dids).eq("status","active").is("unassigned_at",null),admin.from("companies").select("id,name").in("id",cids)]);if(ae)throw ae;if(ce)throw ce;const active=a??[],vids=Array.from(new Set(active.map(x=>x.vehicle_id)));const {data:v,error:ve}=vids.length?await admin.from("vehicles").select("id,name,registration,status").in("id",vids):{data:[],error:null};if(ve)throw ve;const ba=new Map(active.map(x=>[x.driver_id,x])),bv=new Map((v??[]).map(x=>[x.id,x])),bc=new Map((c??[]).map(x=>[x.id,x.name]));const result=rows.map(x=>{const aa=ba.get(x.id)??null,vv=aa?bv.get(aa.vehicle_id)??null:null;return{id:x.id,companyId:x.company_id,companyName:bc.get(x.company_id)??"Client",fullName:x.full_name,licenseNumber:x.license_number,phone:x.phone,status:x.status,createdAt:x.created_at,updatedAt:x.updated_at,activeAssignment:aa?{id:aa.id,assignedAt:aa.assigned_at,vehicle:vv?{id:vv.id,name:vv.name,registration:vv.registration,status:vv.status}:null}:null};});return NextResponse.json({drivers:result,canCreate:manageable,canUpdate:manageable,canDelete:manageable,availableVehicles:av});}catch(e){return caught(e,"[Drivers API GET]");}}
export async function POST(request:NextRequest){try{const {profile,token}=await authenticate(request);if(!canManage(profile))return NextResponse.json({error:"Modification interdite pour ce rôle."},{status:403});const b=await request.json() as Record<string,unknown>,full=typeof b.fullName==="string"?b.fullName.trim():"",vid=typeof b.vehicleId==="string"?b.vehicleId:"",cid=typeof b.companyId==="string"?b.companyId:"",lic=typeof b.licenseNumber==="string"?b.licenseNumber.trim():"",phone=typeof b.phone==="string"?b.phone.trim():"";if(!full)return NextResponse.json({error:"Le nom du conducteur est obligatoire."},{status:400});if(!vid||!cid)return NextResponse.json({error:"La sélection d’un véhicule est obligatoire."},{status:400});const {data,error}=await scopedClient(token).rpc("create_driver_with_assignment",{p_company_id:cid,p_vehicle_id:vid,p_full_name:full,p_license_number:lic||null,p_phone:phone||null});if(error){const mapped=rpcError(`${error.message} ${error.details??""}`);if(mapped)return mapped;throw error;}return NextResponse.json({driverId:data},{status:201});}catch(e){return caught(e,"[Drivers API POST]");}}
export async function PATCH(request:NextRequest){try{const {profile,token}=await authenticate(request);if(!canManage(profile))return NextResponse.json({error:"Modification interdite pour ce rôle."},{status:403});const b=await request.json() as Record<string,unknown>,id=typeof b.driverId==="string"?b.driverId:"",full=typeof b.fullName==="string"?b.fullName.trim():"",vid=typeof b.vehicleId==="string"?b.vehicleId:"",lic=typeof b.licenseNumber==="string"?b.licenseNumber.trim():"",phone=typeof b.phone==="string"?b.phone.trim():"";if(!id)return NextResponse.json({error:"Conducteur obligatoire."},{status:400});if(!full)return NextResponse.json({error:"Le nom du conducteur est obligatoire."},{status:400});if(!vid)return NextResponse.json({error:"La sélection d’un véhicule est obligatoire."},{status:400});const {data,error}=await scopedClient(token).rpc("update_driver_with_assignment",{p_driver_id:id,p_full_name:full,p_license_number:lic||null,p_phone:phone||null,p_vehicle_id:vid});if(error){const mapped=rpcError(`${error.message} ${error.details??""}`);if(mapped)return mapped;throw error;}return NextResponse.json({driverId:data});}catch(e){return caught(e,"[Drivers API PATCH]");}}
export async function DELETE(request:NextRequest){try{const {profile,token}=await authenticate(request);if(!canManage(profile))return NextResponse.json({error:"Suppression interdite pour ce rôle."},{status:403});const b=await request.json() as Record<string,unknown>,id=typeof b.driverId==="string"?b.driverId:"",action=b.action;if(!id)return NextResponse.json({error:"Conducteur obligatoire."},{status:400});if(action!=="unassign"&&action!=="archive")return NextResponse.json({error:"Action invalide."},{status:400});const fn=action==="unassign"?"unassign_driver":"archive_driver";const {data,error}=await scopedClient(token).rpc(fn,{p_driver_id:id});if(error){const mapped=rpcError(`${error.message} ${error.details??""}`);if(mapped)return mapped;throw error;}return NextResponse.json({driverId:data,action});}catch(e){return caught(e,"[Drivers API DELETE]");}}
