"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Car, CheckCircle2, Plus, RefreshCw, Search, UserRound, Users, X, XCircle } from "lucide-react";
import { supabase } from "../../components/supabase";

type DriverRow = { id:string; companyId:string; companyName:string; fullName:string; licenseNumber:string|null; phone:string|null; status:string; createdAt:string; updatedAt:string; activeAssignment:{ id:string; assignedAt:string; vehicle:{ id:string; name:string; registration:string; status:string }|null }|null };
type VehicleOption = { id:string; companyId:string; companyName:string; name:string; registration:string };
type DriverDisplayStatus = "En conduite" | "Disponible" | "Inactif";

function displayStatus(driver:DriverRow):DriverDisplayStatus { if(driver.status!=="active") return "Inactif"; return driver.activeAssignment?.vehicle ? "En conduite" : "Disponible"; }
function statusClasses(status:DriverDisplayStatus){ if(status==="En conduite") return "border-emerald-500/20 bg-emerald-500/10 text-emerald-300"; if(status==="Disponible") return "border-blue-500/20 bg-blue-500/10 text-blue-300"; return "border-slate-700 bg-slate-800 text-slate-400"; }
function initials(name:string){ const p=name.trim().split(/\s+/).filter(Boolean); if(!p.length)return"ND"; if(p.length===1)return p[0].slice(0,2).toUpperCase(); return `${p[0][0]}${p[p.length-1][0]}`.toUpperCase(); }
function formatDate(value:string|null){ if(!value)return"—"; return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Africa/Casablanca"}).format(new Date(value)); }

export default function ConducteursPage(){
 const [drivers,setDrivers]=useState<DriverRow[]>([]); const [vehicles,setVehicles]=useState<VehicleOption[]>([]); const [canCreate,setCanCreate]=useState(false);
 const [search,setSearch]=useState(""); const [statusFilter,setStatusFilter]=useState<"Tous"|DriverDisplayStatus>("Tous"); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState<string|null>(null);
 const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [formError,setFormError]=useState<string|null>(null); const [fullName,setFullName]=useState(""); const [licenseNumber,setLicenseNumber]=useState(""); const [phone,setPhone]=useState(""); const [vehicleId,setVehicleId]=useState("");

 const loadDrivers=useCallback(async(manual=false)=>{ if(manual)setRefreshing(true);else setLoading(true); setError(null); try{ const {data:{session},error:sessionError}=await supabase.auth.getSession(); if(sessionError||!session)throw new Error("Session expirée."); const response=await fetch("/api/drivers",{cache:"no-store",headers:{Authorization:`Bearer ${session.access_token}`}}); const payload=await response.json() as {drivers?:DriverRow[];availableVehicles?:VehicleOption[];canCreate?:boolean;error?:string}; if(!response.ok)throw new Error(payload.error??"Impossible de charger les conducteurs."); setDrivers(payload.drivers??[]);setVehicles(payload.availableVehicles??[]);setCanCreate(Boolean(payload.canCreate)); }catch(e){setDrivers([]);setVehicles([]);setError(e instanceof Error?e.message:"Impossible de charger les conducteurs.");}finally{setLoading(false);setRefreshing(false);}},[]);
 useEffect(()=>{void loadDrivers();},[loadDrivers]);
 const filteredDrivers=useMemo(()=>{const q=search.trim().toLowerCase();return drivers.filter(d=>{const s=displayStatus(d),v=d.activeAssignment?.vehicle;return(statusFilter==="Tous"||s===statusFilter)&&(!q||d.fullName.toLowerCase().includes(q)||(d.phone??"").toLowerCase().includes(q)||(d.licenseNumber??"").toLowerCase().includes(q)||d.companyName.toLowerCase().includes(q)||(v?.name??"").toLowerCase().includes(q)||(v?.registration??"").toLowerCase().includes(q));});},[drivers,search,statusFilter]);
 const stats=useMemo(()=>{let driving=0,available=0,inactive=0;for(const d of drivers){const s=displayStatus(d);if(s==="En conduite")driving++;else if(s==="Disponible")available++;else inactive++;}return{total:drivers.length,driving,available,inactive};},[drivers]);
 const selectedVehicle=vehicles.find(v=>v.id===vehicleId)??null;
 function resetForm(){setFullName("");setLicenseNumber("");setPhone("");setVehicleId("");setFormError(null);}
 async function createDriver(e:React.FormEvent){e.preventDefault();setFormError(null);if(!fullName.trim()){setFormError("Le nom du conducteur est obligatoire.");return;}if(!selectedVehicle){setFormError("Sélectionnez obligatoirement un véhicule.");return;}setSaving(true);try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Session expirée.");const response=await fetch("/api/drivers",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({fullName:fullName.trim(),licenseNumber:licenseNumber.trim(),phone:phone.trim(),vehicleId:selectedVehicle.id,companyId:selectedVehicle.companyId})});const payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error??"Impossible de créer le conducteur.");setOpen(false);resetForm();await loadDrivers(true);}catch(e){setFormError(e instanceof Error?e.message:"Impossible de créer le conducteur.");}finally{setSaving(false);}}

 return <div className="space-y-6">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-blue-500/10"><Users className="h-6 w-6 text-blue-400"/></div><div><h1 className="text-2xl font-semibold text-white">Conducteurs</h1><p className="mt-1 text-sm text-slate-400">Conducteurs et affectations réelles de votre périmètre.</p></div></div><div className="flex gap-3">{canCreate&&<button type="button" onClick={()=>{resetForm();setOpen(true);}} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-blue-500"><Plus className="h-4 w-4"/>Ajouter un conducteur</button>}<button type="button" onClick={()=>void loadDrivers(true)} disabled={refreshing} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 bg-slate-900 px-4 py-2.5 text-sm font-medium text-slate-200 hover:bg-slate-800 disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${refreshing?"animate-spin":""}`}/>Actualiser</button></div></div>
  <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total conducteurs",stats.total,"Enregistrements accessibles","text-white",Users],["En conduite",stats.driving,"Affectation active à un véhicule","text-emerald-400",Car],["Disponibles",stats.available,"Actifs sans affectation","text-blue-400",CheckCircle2],["Inactifs",stats.inactive,"Conducteurs archivés ou désactivés","text-slate-300",XCircle]].map(([label,value,sub,color,Icon])=><div key={String(label)} className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center justify-between"><span className="text-sm text-slate-400">{String(label)}</span>{typeof Icon!=="string"&&<Icon className="h-5 w-5 text-blue-400"/>}</div><p className={`mt-3 text-3xl font-bold ${String(color)}`}>{String(value)}</p><p className="mt-1 text-xs text-slate-500">{String(sub)}</p></div>)}</div>
  <div className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-semibold text-white">Liste des conducteurs</h2><p className="mt-1 text-xs text-slate-500">Aucune donnée de démonstration n’est utilisée sur cette page.</p></div><div className="flex flex-col gap-3 sm:flex-row"><div className="relative min-w-[240px]"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nom, permis, véhicule…" className="w-full rounded-lg border border-slate-700 bg-slate-950 py-2.5 pl-9 pr-3 text-sm text-white outline-none focus:border-blue-500"/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value as "Tous"|DriverDisplayStatus)} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-slate-200"><option value="Tous">Tous les statuts</option><option>En conduite</option><option>Disponible</option><option>Inactif</option></select></div></div>
   {error&&<div className="mt-5 rounded-lg border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-300">{error}</div>}
   {loading?<div className="flex min-h-52 items-center justify-center text-sm text-slate-500">Chargement des conducteurs…</div>:filteredDrivers.length===0?<div className="flex min-h-52 flex-col items-center justify-center text-center"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-slate-800"><UserRound className="h-5 w-5 text-slate-500"/></div><p className="mt-4 text-sm font-medium text-slate-300">{drivers.length===0?"Aucun conducteur enregistré":"Aucun conducteur ne correspond aux filtres"}</p><p className="mt-1 max-w-md text-xs text-slate-500">{drivers.length===0?"La base réelle ne contient actuellement aucun conducteur dans votre périmètre.":"Modifiez la recherche ou le filtre de statut."}</p></div>:<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead><tr className="border-b border-slate-800 text-xs uppercase tracking-wide text-slate-500">{["Conducteur","Client","Permis","Téléphone","Véhicule affecté","Statut","Affecté depuis"].map(h=><th key={h} className="px-3 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{filteredDrivers.map(d=>{const s=displayStatus(d),v=d.activeAssignment?.vehicle;return <tr key={d.id} className="border-b border-slate-800/70 text-sm last:border-0"><td className="px-3 py-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-500/10 text-xs font-semibold text-blue-300">{initials(d.fullName)}</div><div><p className="font-medium text-white">{d.fullName}</p><p className="text-xs text-slate-600">Créé le {formatDate(d.createdAt)}</p></div></div></td><td className="px-3 py-4 text-slate-300">{d.companyName}</td><td className="px-3 py-4 text-slate-300">{d.licenseNumber||"—"}</td><td className="px-3 py-4 text-slate-300">{d.phone||"—"}</td><td className="px-3 py-4">{v?<div><p className="font-medium text-slate-200">{v.name}</p><p className="text-xs text-slate-500">{v.registration}</p></div>:<span className="text-slate-500">Non affecté</span>}</td><td className="px-3 py-4"><span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-medium ${statusClasses(s)}`}>{s}</span></td><td className="px-3 py-4 text-slate-400">{d.activeAssignment?formatDate(d.activeAssignment.assignedAt):"—"}</td></tr>})}</tbody></table></div>}
  </div>
  {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-xl rounded-2xl border border-slate-700 bg-slate-900 shadow-2xl"><div className="flex items-center justify-between border-b border-slate-800 px-6 py-4"><div><h2 className="text-lg font-semibold text-white">Ajouter un conducteur</h2><p className="mt-1 text-xs text-slate-400">Le véhicule est obligatoire et l’affectation est créée immédiatement.</p></div><button onClick={()=>setOpen(false)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-800"><X className="h-5 w-5"/></button></div><form onSubmit={createDriver} className="space-y-4 p-6"><label className="block text-sm text-slate-300">Nom complet *<input value={fullName} onChange={e=>setFullName(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-white outline-none focus:border-blue-500"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm text-slate-300">N° de permis<input value={licenseNumber} onChange={e=>setLicenseNumber(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-white"/></label><label className="block text-sm text-slate-300">Téléphone<input value={phone} onChange={e=>setPhone(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-white"/></label></div><label className="block text-sm text-slate-300">Véhicule à affecter *<select required value={vehicleId} onChange={e=>setVehicleId(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-white"><option value="">Sélectionner obligatoirement un véhicule…</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.companyName} — {v.name} ({v.registration})</option>)}</select></label>{vehicles.length===0&&<p className="rounded-lg border border-amber-500/20 bg-amber-500/10 px-3 py-2 text-xs text-amber-300">Aucun véhicule disponible sans conducteur actif dans votre périmètre.</p>}{formError&&<div className="rounded-lg border border-red-500/20 bg-red-500/10 px-3 py-2 text-sm text-red-300">{formError}</div>}<div className="flex justify-end gap-3 pt-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border border-slate-700 px-4 py-2.5 text-sm text-slate-300">Annuler</button><button type="submit" disabled={saving||!vehicles.length} className="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white disabled:cursor-not-allowed disabled:opacity-50">{saving?"Création…":"Créer et affecter"}</button></div></form></div></div>}
 </div>;
}
