import assert from "node:assert/strict";
import { createConnectionLimiter } from "./connection-limits";
const limiter=createConnectionLimiter(3,2);
assert.equal(limiter.acquire(undefined),null);
const a1=limiter.acquire("ip-a"),a2=limiter.acquire("ip-a");
assert.ok(a1 && a2);
assert.equal(limiter.acquire("ip-a"),null);
const b1=limiter.acquire("ip-b");assert.ok(b1);
assert.equal(limiter.acquire("ip-c"),null);
assert.deepEqual(limiter.snapshot(),{total:3,peers:2});
a1();a1();
assert.deepEqual(limiter.snapshot(),{total:2,peers:2});
const c1=limiter.acquire("ip-c");assert.ok(c1);
a2();b1();c1();
assert.deepEqual(limiter.snapshot(),{total:0,peers:0});
assert.throws(()=>createConnectionLimiter(0,1));
assert.throws(()=>createConnectionLimiter(2,3));
assert.throws(()=>createConnectionLimiter(3,1.5));
console.log("PASS: global and per-IP caps, missing peer denial, idempotent release, peer cleanup and invalid configuration");
